### ISSUE TITLE
ims blob is old for kenzo needs to update it to oreo

### ISSUE THREAD

**Issue by improbir** [TheScarastic/proprietary_vendor_xiaomi#1]
Volte video call is not working because of old blob which is not supported by Android Oreo.

**Comment by ghost** [comment]
Are you asking for new bobs?

**Comment by rk779** [comment]
Sand bobs

**Comment by phantom-1402** [comment]
if you know the reason of the issue.... FIX it... Update the "bob"

**Comment by akhilnarang** [comment]
Hmm ok

**Comment by TheScarastic** [comment]
ayy lmao

**Comment by improbir** [comment]
vendor files are old , problem with video call, sometimes with the gps Its need to be fixed asap.

**Comment by TheScarastic** [comment]
vendor files are old, device doesn't boots, use miui

**Comment by improbir** [comment]
atleast update the lib-imsvt.so blobs file so that kenzo users can do volte video call.

**Comment by akhilnarang** [comment]
NoU

**Comment by rk779** [comment]
nonoU

**Comment by dev-harsh1998** [comment]
Sir @improbir please provide developers with new blobs so he can update it :3
